<font size="6" >Before any main code is run make sure the data folder follow this structure Main_folder -> Individual_ID_folder(each person would have a different folder) -> image</font>

In [7]:
!pip install deepface


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2
import os
from deepface import DeepFace
import numpy as np
import time

In [3]:
KNOWN_FACES_DIR = 'Face testing'

In [4]:
known_faces = []
known_names = []

for person_name in os.listdir(KNOWN_FACES_DIR):
    person_folder = os.path.join(KNOWN_FACES_DIR, person_name)
    
    if not os.path.isdir(person_folder):
        continue
    
    for image_name in os.listdir(person_folder):
        image_path = os.path.join(person_folder, image_name)
        face = DeepFace.represent(img_path=image_path, model_name="VGG-Face")
        known_faces.append(face)
        known_names.append(person_name)

In [5]:
last_recognition_time = 0 

In [6]:

video_capture = cv2.VideoCapture(0)

while True:
    ret, frame = video_capture.read()
    if not ret:
        break

    current_time = time.time()

    #Run the model every 2 seconds and not every frame so my pc can survive
    if current_time - last_recognition_time >= 2:
        last_recognition_time = current_time

        # Perform face recognition
        result = DeepFace.find(frame, db_path=KNOWN_FACES_DIR, model_name="VGG-Face", enforce_detection=False)

        unique_identities = set()
        for df in result:
            if not df.empty:
                identities = df['identity'].tolist()
                unique_identities.update(identities)  

                best_match = df.loc[df['distance'].idxmin()]
                recognized_name = os.path.basename(os.path.dirname(best_match['identity']))
            else:
                print("No matches found.") #Does not work and i got too much on my hand so ill handle that in the assignment

        print("Face Match:", list(unique_identities))  # Convert set to list for display

    cv2.imshow('Face Recognition', cv2.resize(frame, (640, 480)))

    if cv2.waitKey(1) & 0xFF == ord('\r'): 
        break

# Release resources
video_capture.release()
cv2.destroyAllWindows()

24-11-01 16:57:39 - Searching [[[ 81 114 159]
  [ 82 111 159]
  [ 77 101 154]
  ...
  [143 156 161]
  [137 155 165]
  [137 155 165]]

 [[ 81 110 155]
  [ 80 106 154]
  [ 77  99 150]
  ...
  [140 154 159]
  [136 154 165]
  [138 156 167]]

 [[ 89 112 158]
  [ 79 100 147]
  [ 80  98 147]
  ...
  [146 160 167]
  [136 153 167]
  [138 156 169]]

 ...

 [[179 180 204]
  [176 183 206]
  [172 185 207]
  ...
  [166 156 153]
  [163 155 151]
  [163 155 151]]

 [[175 182 201]
  [172 184 204]
  [164 181 201]
  ...
  [171 159 157]
  [170 157 152]
  [170 157 152]]

 [[171 181 198]
  [171 185 203]
  [166 185 204]
  ...
  [168 154 152]
  [172 157 152]
  [171 156 151]]] in 9 length datastore
24-11-01 16:57:40 - find function duration 0.33986449241638184 seconds
Face Match: ['Face testing\\Binh\\Binh1.jpg', 'Face testing\\Binh\\Binh6.jpg', 'Face testing\\Binh\\Binh4.jpg', 'Face testing\\Binh\\Binh3.jpg']
24-11-01 16:57:41 - Searching [[[ 83 101 129]
  [ 79 100 129]
  [ 81 104 133]
  ...
  [163 172 156]
  